Add TLS options for custom trusted certs and insecure connections. (#20)
## Motivation
I would love to be able to use this provider but the cert on our endpoint is self-signed and as such I encountered the following error:
```
Error: ERROR_READ_TENANT: Get "https://[REDACTED]/admin/v2/tenants/public": x509: certificate signed by unknown authority
```
Adding it to the host system is possible but cumbersome for some use-cases (particularity when working with multiple clusters in a CI/CD environment.) Since this functionality is already available in the upstream package (and supported by existing pulsar clients) seemed like a good idea to add it to the provider.

## Modifications
* Adds `tls_trust_certs_file_path` to enable provider usage with custom certs (ie self-signed certs) and to better align provider config options with pulsar client config options.
* Adds `tls_allow_insecure_connection` to enable provider usage with custom certs _during development_.